version: "0.2"
language: en
ignorePaths:
  - "**/node_modules/**"
  # The prh dictionary lists misspellings on purpose
  - .textlintprh.yaml
words:
  - amzn
  - Anson
  - anthropics
  - apimachinery
  - Bainbridge
  - benchmem
  - Berryman
  - biasable
  - bpmndi
  - bpmnlint
  - bpmnlintrc
  - Chollet
  - Cialdini
  - coji
  - Csikszentmihalyi
  - Cura
  - danvega
  - databind
  - dearu
  - desumasu
  - docsify
  - esbenp
  - fasterxml
  - Ferrazzi
  - Fournier
  - goarch
  - gofrs
  - goos
  - goroutineleak
  - gouuid
  - gson
  - guuid
  - halfwidth
  - hediet
  - hibits
  - Housley
  - hpp
  - Huyen
  - imgs
  - jcmd
  - joshi
  - jsa
  - Keras
  - Kleppmann
  - Kousen
  - Lilliput
  - Masterplan
  - modernc
  - Mollick
  - msecs
  - Nadel
  - nakaguro
  - neild
  - nocoh
  - Norming
  - Norvig
  - noto
  - ntschutta
  - Osmani
  - pborman
  - pprof
  - Pramod
  - println
  - Reis
  - reviewdog
  - rhumie
  - Riccomini
  - Sadalage
  - SapMachine
  - Schutta
  - sdkman
  - sdkmanrc
  - shengchen
  - Souza
  - SSKDs
  - Subramaniam
  - Tahl
  - textlint
  - textlintprh
  - Thoughtworks
  - Tidwell
  - trixie
  - Udemy
  - unreflect
  - Valhalla
  - vscjava
  - Wielenga
  - womens
