version: "0.2"
language: en
words:
  - amzn
  - apimachinery
  - benchmem
  - databind
  - docsify
  - fasterxml
  - goarch
  - gofrs
  - goos
  - goroutineleak
  - gouuid
  - gson
  - guuid
  - hibits
  - modernc
  - msecs
  - neild
  - Norming
  - pborman
  - pprof
  - println
  - reviewdog
  - sdkman
  - sdkmanrc
  - SSKDs
  - textlint
  - unreflect
  - womens
