version: "0.2"
language: en
ignorePaths:
  - "**/node_modules/**"
  # The prh dictionary lists misspellings on purpose
  - .textlintprh.yaml
words:
  - amzn
  - Anson
  - anthropics
  - apimachinery
  - Bainbridge
  - benchmem
  - biasable
  - bpmndi
  - bpmnlint
  - bpmnlintrc
  - coji
  - databind
  - dearu
  - desumasu
  - docsify
  - esbenp
  - fasterxml
  - goarch
  - gofrs
  - goos
  - goroutineleak
  - gouuid
  - gson
  - guuid
  - halfwidth
  - hediet
  - hibits
  - hpp
  - imgs
  - jcmd
  - joshi
  - jsa
  - Lilliput
  - modernc
  - msecs
  - nakaguro
  - neild
  - nocoh
  - Norming
  - noto
  - pborman
  - pprof
  - println
  - reviewdog
  - rhumie
  - SapMachine
  - sdkman
  - sdkmanrc
  - shengchen
  - SSKDs
  - textlint
  - textlintprh
  - trixie
  - unreflect
  - Valhalla
  - vscjava
  - womens
