version: 1

imports:
  - "node_modules/prh/prh-rules/media/WEB+DB_PRESS.yml"

rules:
  # Overwrite existing rules
  - expected: 始め
  - expected: はじめに
    pattern: 始めに

  - expected: メンバー
  - expected: メンバ
    pattern: メンバー

  - expected: ユーザー$1
  - expected: ユーザ
    pattern: ユーザー
